[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    mobizt/FirebaseClient
    bblanchon/ArduinoJson

build_flags =
    -DFIREBASE_DATABASE_URL=\"${sysenv.FIREBASE_DATABASE_URL}\"
    -DFIREBASE_API_KEY=\"${sysenv.FIREBASE_API_KEY}\"
    -DFIREBASE_AUTH_EMAIL=\"${sysenv.FIREBASE_AUTH_EMAIL}\"
    -DFIREBASE_AUTH_PASSWORD=\"${sysenv.FIREBASE_AUTH_PASSWORD}\"
    -DCONFIG_DEVICE_ID=\"esp32_device_1\"
    -DCONFIG_PLANT_ID=\"plant_colombo\"